version: '3.8'

services:
  ollama: 
    container_name: ollama
    build: 
      context: ./ollama-docker
      dockerfile: ./Dockerfile
    ports: 
      - 11434:11434
  streamlit-app: 
    container_name: streamlit-gita
    build: 
      context: ./streamlit-docker
      dockerfile: ./Dockerfile
    ports:
      - 8500:8500
    depends_on:
      - ollama



